modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/mccreery/hotswap/issues"

[[mods]]
modId="hotswap"
version="${file.jarVersion}"
displayName="HotSwap"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hotswap"
authors="jobicade"
description="Quickly switch out hotbars from your inventory with a single keypress or mouse."
